# NOTE: some packages get installed directly in Makefile, such as
#   in target bash:
#     bash / bash completion / pcre
#   in target git:
#     git / git-extras
#   in target mise:

tap "homebrew/bundle"
tap "lotyp/homebrew-formulae"

# core/dotfiles
brew "bats-core"
brew "coreutils" # provide cat/ls etc from coreutils instead of macos
brew "duti" # set default app for filetype; see install/duti
brew "lotyp/formulae/dockutil" # configure mac dock, see macos/dock
brew "stow" # installs packages in its own dir and symlink to there
brew "topgrade"

# fs/network
brew "bat" # cat but with syntax highlighting
brew "croc" # secure file transfers, across computers
brew "tree" # recursive ls
brew "wget"
brew "zoxide" # smart replacement to cd, via `z`

# search/grep/diff
brew "fd" # for telescope (nvim) and others
brew "fzf" # fuzzy file finder
brew "gnu-sed"
brew "ripgrep" # regex-based search via rg, super fast
brew "the_silver_searcher" # search via ag <search-term>

# Tmux
brew "reattach-to-user-namespace"
brew "tmux"
brew "tmuxinator"

# Editors
brew "vim"
brew "nvim"

# Git - other than installed in Make git target
brew "gh" # Github command line tool
brew "git-delta" # nicer syntax highlighting for git diff
