# Enable 256 color support
set -g default-terminal "screen-256color"
set-window-option -g xterm-keys on

# Use Ctrl+B as prefix key (default)
set -g prefix C-b
bind C-b send-prefix

# Remove delay when pressing escape key
set -s escape-time 0

# Increase scrollback buffer size
set -g history-limit 50000

# Update status bar every 5 seconds
set -g status-interval 5

# Aggressively resize windows
setw -g aggressive-resize on

# Enhance status bar
setw -g automatic-rename-format "#P #{pane_current_path}  #{pane_current_command}"

# Don't exit tmux after kill-session
set-option -g detach-on-destroy off

# Remove right status bar content
set -g status-right ''

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber windows when one is closed
set -g renumber-windows on

# Reload this config with 'prefix + r'
bind r source-file $HOME/.dotfiles/config/tmux/.tmux.conf \; display "Config reloaded"

# Enable mouse support
set -g mouse on

# Use vi keybindings in copy mode
setw -g mode-keys vi
